<a href="https://colab.research.google.com/github/SamayMody/Data-Science/blob/main/data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 1

In [ ]:
import numpy as np
import random

# Perform min max sum using np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the sum of the array
sum_arr = np.sum(arr)

# Calculate the minimum and maximum values of the array
min_val = np.min(arr)
max_val = np.max(arr)

# Calculate the sum of the minimum and maximum values
sum_min_max = min_val + max_val

# Print the results
print("Sum of the array:", sum_arr)
print("Sum of the minimum and maximum values:", sum_min_max)


Sum of the array: 15
Sum of the minimum and maximum values: 6


In [ ]:
B = np.random.randint(0, 100, size=(3, 3))
print("B:", B)
print("")
print("Shape of B:", B.shape)
print("")
print("Size of B:", B.size)
print("")
print("Dimension of B:", B.ndim)

B: [[22 95  6]
 [96 64 51]
 [89 27 16]]

Shape of B: (3, 3)

Size of B: 9

Dimension of B: 2


# Day 2

In [ ]:
C = np.array([12.3 , 34.2 , 5.3])
print("C:", C)

C: [12.3 34.2  5.3]


In [ ]:
# To use array slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

[2 3 4]


In [28]:
# to use zeros and ones anf full function
arr3 = np.zeros(5)
arr4 = np.ones(5)
arr5 = np.full(5, 3)
print(arr3)
print(arr4)
print(arr5)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[3 3 3 3 3]


# Day 3

In [ ]:
# To use mathemethical functions
arr2 = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr2))
print(np.exp(arr2))
print(np.log(arr2))
print(np.sin(arr2))
print(np.cos(arr2))
print(np.tan(arr2))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [ ]:
# using assignment operator
arr6 = np.array([1, 2, 3, 4, 5])
arr6 += 2
print(arr6)

[3 4 5 6 7]


In [ ]:
# iterating arrays
arr7 = np.array([1, 2, 3, 4, 5])
for x in arr7:
    print(x)

1
2
3
4
5


In [ ]:
# reshaping 1d to 2d
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr8.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Day 4

In [ ]:
# using vstack and hstack
arr10 = np.array([1, 2, 3])
arr11 = np.array([4, 5, 6])
arr12 = np.vstack((arr10, arr11))
print(arr12)
arr13 = np.hstack((arr10, arr11))
print(arr13)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# using split()
arr14 = np.array([1, 2, 3, 4, 5, 6])
newarr1 = np.array_split(arr14, 3)
print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# using poission distribution, uniform distribution, chi-square distribution, binomial distribution, exponential
arr15 = np.random.poisson(lam=2, size=10)
print(arr15)
arr16 = np.random.uniform(low=0.0, high=1.0, size=10)
print(arr16)
arr17 = np.random.chisquare(df=2, size=10)
print(arr17)
arr18 = np.random.binomial(n=10, p=0.5, size=10)
print(arr18)
arr19 = np.random.exponential(scale=1.0, size=10)
print(arr19)

[2 2 2 1 2 1 1 0 2 3]
[0.99327739 0.65609653 0.11752291 0.64350589 0.15229556 0.57055379
 0.9666405  0.20151993 0.34662843 0.84587449]
[8.56906994 0.38199794 2.23030288 0.92674712 0.41670225 4.4926235
 0.34837375 2.58229392 1.18135492 1.88604209]
[6 5 4 3 3 6 4 4 5 6]
[2.07096168 0.96013993 1.08983    2.34728156 0.08321548 0.09325828
 0.77886766 0.19755204 0.12758304 1.03119519]
